// Generated by scripts/setup-private.mjs — contains ciphertext only, safe to commit.
window.VAULT = {"v":1,"iter":600000,"salt":"0vFdr7M/PaMN859cN8pv4A==","iv":"ThU2v2/AcVn3vxQ9","ct":"mQaojkSsvydDMJk4atpHcwe0xx3nOiS8wPlbe0MzfvKyaQtYOgpUceHkkexQCasDGXQax72HO2cvFc4Af/0nlm3Nd4AHo+bxTJ8bU8Z/1pgL"};
