// Generated by scripts/setup-private.mjs — contains ciphertext only, safe to commit.
window.VAULT = {"v":1,"iter":600000,"salt":"3+nwIzgPusQmu/OqrSpPTA==","iv":"eTyXk7I/y3APmNa8","ct":"Bhs5J3amizb5ue/1WaUQK/HfsO61deOo0Lze0lefzmcO3TXEB1Kk7UiR/BWIAs8VGALVNsiGabFwVuytOjyTdBVawbpj1mbKodbWabfBSUls"};
